clear all;
close all;
clc;

fL = 8000;
Fs=16000;
% fr = dsp.AudioFileReader(...
%     'salida_canal.wav',...
%     'SamplesPerFrame',fL);%poner fL/2 en caso de que la Fs de la cancion esté a la mitad de la Fs de reproduccion
deviceReader = audioDeviceReader(...
    'SamplesPerFrame',fL,...
    'SampleRate',Fs);
setup(deviceReader);

deviceWriter = audioDeviceWriter(...
    'SampleRate',Fs/2);

scope_t_c = dsp.TimeScope(...
    'Name','Señal recibida del canal',...
    'SampleRate',Fs,...
    'TimeSpan',fL/Fs,...
    'BufferLength',1e6,...
    'YLimits',[-1.1 1.1]);

scope_f_c = dsp.SpectrumAnalyzer(...
    'Name','Espectro de señal recibida del canal',...
    'SampleRate',Fs,...
    'SpectralAverages',1,...
    'PlotAsTwoSidedSpectrum',false,...
    'RBWSource','Auto');

while 1
    signal = deviceReader();
    scope_t_c(signal);
    scope_f_c(signal);
end
release(udpr);